/* __________________DROP_____________________ */
DROP TABLE cliente CASCADE CONSTRAINTS;

DROP TABLE telefono CASCADE CONSTRAINTS;

DROP TABLE cliente_vip CASCADE CONSTRAINTS;

DROP TABLE venta CASCADE CONSTRAINTS;

DROP TABLE linea_venta CASCADE CONSTRAINTS;

DROP TABLE personal CASCADE CONSTRAINTS;

DROP TABLE telefono_personal CASCADE CONSTRAINTS;

DROP TABLE farmaceutico CASCADE CONSTRAINTS;

DROP TABLE cajero CASCADE CONSTRAINTS;

DROP TABLE sucursal CASCADE CONSTRAINTS;

DROP TABLE ceo CASCADE CONSTRAINTS;

DROP TABLE telefono_ceo CASCADE CONSTRAINTS;

DROP TABLE item CASCADE CONSTRAINTS;

DROP TABLE producto CASCADE CONSTRAINTS;

DROP TABLE medicamento CASCADE CONSTRAINTS;

DROP TABLE empresa CASCADE CONSTRAINTS;

DROP TABLE telefono_empresa CASCADE CONSTRAINTS;

DROP TABLE laboratorio CASCADE CONSTRAINTS;


DROP TABLE proveedor CASCADE CONSTRAINTS;

/* __________________TABLAS_____________________ */

CREATE TABLE CLIENTE(
	CDNI		VARCHAR(9) NOT NULL,
	CNAME		VARCHAR(25),
	CDIR		VARCHAR(255),
	CNSS		VARCHAR(12),
		PRIMARY KEY (CDNI),
);

CREATE TABLE TLF_C(
	CDNI		VARCHAR(9) NOT NULL,
	CTLF		INT(9) NOT NULL,
		PRIMARY KEY (CDNI, CTLF),
		FOREIGN KEY (CDNI) REFERENCES CLIENTE
);

CREATE TABLE CLIENTE_VIP(
	CDNI		VARCHAR(9) NOT NULL,
	CODIGO_EMP	INT(9) NOT NULL,
	DESC		INT(2),
		PRIMARY KEY (CDNI, CODIGO_EMP),
		FOREIGN KEY (CDNI) REFERENCES CLIENTE,
		FOREIGN KEY (CODIGO_EMP) REFERENCES PERSONAL,
);

CREATE TABLE VENTA(
	CODIGO_VENTA	INT() NOT NULL,
	DNI		VARCHAR(9) NOT NULL,
	CODIGO_EMP	INT(9) NOT NULL,
		PRIMARY KEY (CODIGO_VENTA),
		FOREIGN KEY (DNI) REFERENCES CLIENTE,
		FOREIGN KEY (CODIGO_EMP) REFERENCES PERSONAL,
);

CREATE TABLE LINEA_VENTA(
	N_SEC		INT() NOT NULL,
	CODIGO_VENTA	INT() NOT NULL,
	COD_ITEM	INT() NOT NULL,
	CANTIDAD	INT() NOT NULL,
		PRIMARY KEY(N_SEC,CODIGO_VENTA),
		FOREIGN KEY (CODIGO_VENTA) REFERENCES VENTA,
		FOREIGN KEY (COD_ITEM) REFERENCES ITEM,
);

CREATE TABLE PERSONAL (
	CODIGO_EMP	INT() NOT NULL,
	DNI		VARCHAR(9) NOT NULL,
	NOMBRE		VARCHAR(25) NOT NULL,
	DIR		VARCHAR(255) NOT NULL,
	DNI_SUPERVISOR	VARCHAR(9) NOT NULL,
	NUM_SUC		INT() NOT NULL,
		PRIMARY KEY(CODIGO_EMP),
		FOREIGN KEY (DNI_SUPERVISOR) REFERENCES PERSONAL,
		FOREIGN KEY (NUM_SUC) REFERENCES SUCURSAL,
);

CREATE TABLE TLF_P(
	CODIGO_EMP	INT(9) NOT NULL,
	CTLF		INT(9) NOT NULL,
		PRIMARY KEY (CODIGO_EMP, CTLF),
		FOREIGN KEY (CODIGO_EMP) REFERENCES PERSONAL
);

CREATE TABLE FARMACEUTICO(
	CODIGO_EMP	INT(9) NOT NULL,
	NUM_COLEGIADO	INT() NOT NULL,
		PRIMARY KEY (CODIGO_EMP),
		FOREIGN KEY (CODIGO_EMP) REFERENCES PERSONAL
);

CREATE TABLE CAJERO(
	CODIGO_EMP	INT(9) NOT NULL,
	NUM_CAJA	INT() NOT NULL,
		PRIMARY KEY (CODIGO_EMP),
		FOREIGN KEY (CODIGO_EMP) REFERENCES PERSONAL
);

CREATE TABLE SUCURSAL(
	NUM_SUC		INT() NOT NULL,
	DIREC		VARCHAR(255),
		PRIMARY KEY (NUM_SUC),
);

CREATE TABLE CEO(
	DNI		VARCHAR(9) NOT NULL,
	NOMBRE		VARCHAR(25),
		PRIMARY KEY (DNI),
);

CREATE TABLE TLF_CEO(
	DNI		VARCHAR(9) NOT NULL,
	TLF		INT(9) NOT NULL,
		PRIMARY KEY (DNI, TLF),
		FOREIGN KEY (DNI) REFERENCES CEO
);

CREATE TABLE ITEM(
	CODIGO_ITEM	INT() NOT NULL,
	PRECIO		FLOAT() NOT NULL,
	NOMBRE		VARCHAR(25) NOT NULL,
	STOCK		INT() NOT NULL,
		PRIMARY KEY (CODIGO_ITEM),
);

CREATE TABLE PRODUCTO(
	CODIGO_ITEM	INT() NOT NULL,
	TIPO_P		VARCHAR() NOT NULL,
		PRIMARY KEY (CODIGO_ITEM),
		FOREIGN KEY (CODIGO_ITEM) REFERENCES ITEM
);

CREATE TABLE MEDICAMENTO(
	CODIGO_ITEM	INT() NOT NULL,
	COD_NAC		INT() NOT NULL,
	TIPO_M		VARCHAR() NOT NULL,
	FECHA_CAD	DATE,
		PRIMARY KEY (CODIGO_ITEM),
		FOREIGN KEY (CODIGO_ITEM) REFERENCES ITEM
);

CREATE TABLE EMPRESA(
	ID_EMP		INT() NOT NULL,
	DIR		VARCHAR(255) NOT NULL,
	NOMBRE		VARCHAR(25) NOT NULL,
		PRIMARY KEY(ID_EMP)
);

CREATE TABLE TLF_EMP(
	ID_EMP		INT() NOT NULL,
	TLF		INT(9) NOT NULL,
		PRIMARY KEY (ID_EMP, TLF),
		FOREIGN KEY (ID_EMP) REFERENCES EMPRESA
);

CREATE TABLE LABORATORIO(
	CODIGO_EMP	INT() NOT NULL,
	CERTI_PRODUC	INT() NOT NULL,
		PRIMARY KEY (CODIGO_EMP),
		FOREIGN KEY (CODIGO_EMP) REFERENCES EMPRESA
);

CREATE TABLE PROVEEDOR(
	CODIGO_EMP	INT() NOT NULL,
	CERTI_PRODUCCION	INT() NOT NULL,
		PRIMARY KEY (CODIGO_EMP),
		FOREIGN KEY (CODIGO_EMP) REFERENCES EMPRESA
);

/* __________________VISTAS_____________________ */
Vista no actualizable-> item-> muestra los productos en stock, no es necesario que se actualice 
ya que entrarán pocos productos nuevos a la farma una vez estabilizado el flujo de personal
CREATE VIEW
	vista_cliente AS
	SELECT
		DNI, NOMBRE, DIR, NSS, TLF
	FROM 
		cliente;

Vista actualizable -> cliente -> muestra y añade nuevos clientes, es necesario que se actualice 
ya que cada vez que venga un nuevo cliente este se debe añadir a la base de datos y a veces habrá 
que modificar datos de clientes habituales.
CREATE VIEW VistaItemDetallada AS
	SELECT i.Codigo, i.Nombre, i.Precio, COUNT(lv.Item_codigo) AS NumeroDeVentas
	FROM Item i
	LEFT JOIN LineaDeVenta lv ON i.Codigo = lv.Item_codigo
	GROUP BY i.Codigo, i.Nombre, i.Precio;

/* __________________ÍNDICES_____________________ */

/* __________________SEED_____________________ */
/* TABLA - CLIENTE */

/* TABLA - TLF_C  */

/* TABLA - CLIENTE_VIP  */

/* TABLA - VENTA  */

/* TABLA - LINEA_VENTA  */

/* TABLA - PERSONAL  */

/* TABLA - TLF_P  */

/* TABLA - FARMACEUTICO  */

/* TABLA - CAJERO  */

/* TABLA - SUCURSAL  */

/* TABLA - CEO  */

/* TABLA - TLF_CEO  */

/* TABLA - ITEM  */

/* TABLA - PRODUCTO  */

/* TABLA - MEDICAMENTO  */

/* TABLA - EMPRESA  */

/* TABLA - TLF_EMP  */

/* TABLA - LABORATORIO  */

/* TABLA - PROVEEDOR  */
